export const events = [
  {
    title: "AI & Machine Learning Summit 2025",
    image: "/images/event1.png",
    slug: "ai-ml-summit-2025",
    location: "San Francisco, CA",
    date: "March 15, 2025",
    time: "09:00 AM",
  },
  {
    title: "Global Cloud Computing Expo",
    image: "/images/event2.png",
    slug: "global-cloud-expo",
    location: "London, UK",
    date: "April 20, 2025",
    time: "10:00 AM",
  },
  {
    title: "Full Stack Developer Conference",
    image: "/images/event3.png",
    slug: "full-stack-conf",
    location: "New York, NY",
    date: "May 10, 2025",
    time: "09:30 AM",
  },
  {
    title: "Cybersecurity World Congress",
    image: "/images/event4.png",
    slug: "cybersecurity-congress",
    location: "Berlin, Germany",
    date: "June 5, 2025",
    time: "08:45 AM",
  },
  {
    title: "Blockchain & Web3 Future",
    image: "/images/event5.png",
    slug: "blockchain-web3-future",
    location: "Singapore",
    date: "July 22, 2025",
    time: "11:00 AM",
  },
  {
    title: "DevOps & SRE Annual Meetup",
    image: "/images/event6.png",
    slug: "devops-sre-meetup",
    location: "Austin, TX",
    date: "August 18, 2025",
    time: "02:00 PM",
  },
];
